// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlj2mRYlTRid0Z36hFORYx46SRs7bW6mU',
    appId: '1:114977160998:web:3872ef450906b32d27cbe7',
    messagingSenderId: '114977160998',
    projectId: 'flutter-full-news-6c99d',
    authDomain: 'flutter-full-news-6c99d.firebaseapp.com',
    storageBucket: 'flutter-full-news-6c99d.appspot.com',
    measurementId: 'G-W8X7NBRTEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAfQWzn14V0gFIAgj7e897NH_cUkgYCHY',
    appId: '1:114977160998:android:3f8c8b426463439c27cbe7',
    messagingSenderId: '114977160998',
    projectId: 'flutter-full-news-6c99d',
    storageBucket: 'flutter-full-news-6c99d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9j_dzwBiL0lQS199R9gIbHWRWVl71wmk',
    appId: '1:114977160998:ios:abaaec88d5956b2d27cbe7',
    messagingSenderId: '114977160998',
    projectId: 'flutter-full-news-6c99d',
    storageBucket: 'flutter-full-news-6c99d.appspot.com',
    iosClientId: '114977160998-o5jh86e897gkd8scj4f2d3u4tk08m0i1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseNewsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9j_dzwBiL0lQS199R9gIbHWRWVl71wmk',
    appId: '1:114977160998:ios:abaaec88d5956b2d27cbe7',
    messagingSenderId: '114977160998',
    projectId: 'flutter-full-news-6c99d',
    storageBucket: 'flutter-full-news-6c99d.appspot.com',
    iosClientId: '114977160998-o5jh86e897gkd8scj4f2d3u4tk08m0i1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseNewsApp',
  );
}
